language: go

go:
  - 1.1
  - 1.2
  - 1.3

notifications:
  email: false

services:
  - redis

script: go test -v

install:
  - go get -u github.com/adjust/redis
  - go get -u github.com/matttproud/gocheck
